[package]
name = "wac"
description = "A tool for encoding and decoding WebAssembly compositions."
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
categories = { workspace = true }
keywords = { workspace = true }
repository = { workspace = true }

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Peter Huene <peter@huene.dev>"]
license = "Apache-2.0 WITH LLVM-exception"
categories = ["wasm"]
keywords = ["webassembly", "wasm", "components", "component-model"]
repository = "https://github.com/bytecodealliance/wac"

[dependencies]
wac-parser = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
pretty_env_logger = { workspace = true }
log = { workspace = true }
tokio = { workspace = true }
owo-colors = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[features]
default = []
wat = ["wac-parser/wat"]

[workspace.dependencies]
wac-parser = { path = "crates/wac-parser", default-features = false }
wit-parser = "0.12.1"
wasmparser = "0.115.0"
wit-component = "0.16.0"
anyhow = "1.0.75"
clap = { version = "4.4.6", features = ["derive"] }
pest = "2.7.4"
pest_derive = "2.7.4"
from-pest = "0.3.2"
pest-ast = "0.3.4"
semver = "1.0.20"
pretty_env_logger = "0.5.0"
log = "0.4.20"
tokio = { version = "1.33.0", default-features = false, features = ["macros", "rt-multi-thread"] }
owo-colors = "3.5.0"
indexmap = { version = "2.0.2", features = ["serde"] }
id-arena = "2.2.1"
serde = { version = "1.0.189", features = ["derive"] }
serde_json = "1.0.107"
wat = "1.0.77"
