[package]
name = "wac"
version = "0.1.0"
edition = "2021"
authors = ["Peter Huene <peter@huene.dev>"]
description = "A tool for encoding and decoding WebAssembly compositions."
license = "Apache-2.0 WITH LLVM-exception"
documentation = "https://docs.rs/wac"
categories = ["wasm"]
keywords = ["webassembly", "wasm", "components", "component-model"]
repository = "https://github.com/bytecodealliance/wac"

[dependencies]
wac-parser = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
pretty_env_logger = { workspace = true }
log = { workspace = true }
tokio = { workspace = true }
owo-colors = { workspace = true }

[workspace.dependencies]
wac-parser = { path = "crates/wac-parser" }
anyhow = "1.0.75"
clap = { version = "4.4.3", features = ["derive"] }
pest = "2.7.3"
pest_derive = "2.7.3"
from-pest = "0.3.2"
pest-ast = "0.3.4"
semver = "1.0.18"
pretty_env_logger = "0.5.0"
log = "0.4.20"
tokio = { version = "1.32.0", default-features = false, features = ["macros", "rt-multi-thread"] }
owo-colors = "3.5.0"
id-arena = "2.2.1"
